import os

DATA_DIR = "data"
CACHE_DURATION_SECONDS = 60 * 60
ALLOW_STALE_SECONDS = 60 * 60 * 24
DATA_RETENTION_DAYS = 730
REFRESH_MIN_INTERVAL_SECONDS = 60

EMA_FAST_5 = 5
EMA_FAST_10 = 10
EMA_SHORT_PERIOD = 20
EMA_LONG_PERIOD = 50
ADX_PERIOD = 14
RSI_PERIODS = (7, 14, 21)

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9

BOLL_PERIOD = 20
BOLL_STD = 2

KDJ_PERIOD = 9
KDJ_SIGNAL_K = 3
KDJ_SIGNAL_D = 3

ATR_PERIOD = 14

RESONANCE_GOLDEN_CROSS_LOOKBACK = 15
RESONANCE_PULLBACK_LOOKBACK = 3
RESONANCE_VOLUME_MA_WINDOW = 20
RESONANCE_VOLUME_SHRINK_RATIO = 0.8
RESONANCE_ESTABLISHED_TREND_LOOKBACK = 80
RESONANCE_ATR_STOP_MULTIPLIER = 1.5
RESONANCE_ATR_TARGET_MULTIPLIER = 3.0

RSI_THRESHOLDS = {
    "uptrend_strong": (75, 45),
    "downtrend_strong": (60, 25),
    "default": (70, 30),
}

CHART_DAYS = 100
MINI_CHART_DAYS = 30

if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)
